name: Build and Upload Python Wheel to GitHub Release

on:
  release:
    types:
      - published

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install required tools
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip build

      # Step 4: Fix multiple top-level package issue in pyproject.toml (Optional)
      - name: Fix Packaging Configuration
        run: |
          echo "
          [build-system]
          requires = ['setuptools', 'wheel']
          build-backend = 'setuptools.build_meta'

          [tool.setuptools.packages.find]
          include = ['ts*', 'cs*', 'js*', 'php*', 'wiki*']
          " > pyproject.toml

      # Step 5: Build the package
      - name: Build Wheel and Source Distribution
        run: |
          python -m build --wheel --sdist

      # Step 6: Upload the wheel to GitHub Release
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.ACCESS_TOKEN }}
