name: Build and Upload Python Wheel to GitHub Release

on:
  release:
    types:
      - published

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build Wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
