name: Upload Python Wheel to GitHub Release

on:
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install required tools
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Step 4: Fix multiple top-level package issue in setup.py
      - name: Fix Setup.py
        run: |
          echo "
          from setuptools import setup, find_packages

          setup(
              name='ccxt-custom',
              packages=find_packages(include=['ts*', 'cs*', 'js*', 'php*', 'wiki*']),
              # Adjust metadata as needed
              description='ccxt package custom',
              author='eq19',
              author_email='eq19@users.noreply.github.com',
              url='https://github.com/KernelPatterns/ccxt',
          )
          " > setup.py

      # Step 5: Build the wheel
      - name: Build Wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Resolve Wheel Path
        id: resolve_wheel
        run: |
          WHEEL_FILE=$(ls dist/ccxt_*.whl | head -n 1)
          if [ -z "$WHEEL_FILE" ]; then
            echo "Wheel file not found in dist/ directory."
            exit 1
          fi
          echo "Resolved wheel file: $WHEEL_FILE"
          echo 'wheel='$WHEEL_FILE >> ${GITHUB_ENV}
          echo 'basename='$(basename($WHEEL_FILE)) >> ${GITHUB_ENV}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./${{ env.wheel }}
          asset_name: ${{ env.basename }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/octet-stream
