name: Build and Release Custom Freqtrade Wheel

on:
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Build Tools
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip build setuptools wheel

    - name: Build Wheel
      run: |
        source venv/bin/activate
        python -m build
        ls -la dist

    - name: Verify Wheel File
      run: |
        if [ -z "$(ls dist/freqtrade-*.whl 2>/dev/null)" ]; then
          echo "Wheel file not found in dist/"
          exit 1
        fi

    - name: Resolve Wheel Path
      id: resolve_wheel
      run: |
        WHEEL_FILE=$(ls dist/freqtrade-*.whl | head -n 1)
        if [ -z "$WHEEL_FILE" ]; then
          echo "Wheel file not found in dist/ directory."
          exit 1
        fi
        echo "Resolved wheel file: $WHEEL_FILE"
        echo 'wheel='$WHEEL_FILE >> ${GITHUB_ENV}
        echo 'basename='basename($WHEEL_FILE) >> ${GITHUB_ENV}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ./${{ env.wheel }}
        asset_name: ${{ env.basename }}
        upload_url: ${{ github.event.release.upload_url }}
        asset_content_type: application/octet-stream
